In [1]:
import pandas as pd
import numpy as np
import time
import datetime

In [2]:
path = 'resources/attacks.csv'

In [3]:
# Reading attacks dataset. Source: https://stackoverflow.com/questions/42339876/error-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xff-in-position-0-in
attacks_raw_df = pd.read_csv(path, encoding='cp1252')

In [4]:
attacks_raw_df.head()

,Country,Case_Number,Date,Year,Type,Area,Location,Activity,Name,Sex,Age,Injury,Fatal_Y_N,Time,Species,Investigator_ or_ Source,pdf,href
0,USA,2018.06.25,6/25/2018,2018.0,Boating,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,USA,2018.06.18,6/18/2018,2018.0,Unprovoked,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,USA,2018.06.09,6/9/2018,2018.0,Invalid,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,AUSTRALIA,2018.06.08,6/8/2018,2018.0,Unprovoked,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,MEXICO,2018.06.04,6/4/2018,2018.0,Provoked,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

In [21]:
# Drop irrelevant columns
attacks_df = attacks_raw_df.drop(
    ['Name', 'Investigator_ or_ Source', 'pdf', 'href'], axis=1)

In [22]:
attacks_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6302 entries, 0 to 6301
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Country      6252 non-null   object
 1   Case_Number  6302 non-null   object
 2   Date         6302 non-null   object
 3   Year         6300 non-null   float64
 4   Type         6298 non-null   object
 5   Area         5847 non-null   object
 6   Location     5762 non-null   object
 7   Activity     5758 non-null   object
 8   Sex          5737 non-null   object
 9   Age          3471 non-null   object
 10  Injury       6274 non-null   object
 11  Fatal_Y_N    5763 non-null   object
 12  Time         2948 non-null   object
 13  Species      3464 non-null   object
dtypes: float64(1), object(13)
memory usage: 689.4+ KB

In [23]:
# Keep only unprovoked attacks
unprovoked_attacks_df = attacks_df[attacks_df['Type'] == "Unprovoked"]

In [24]:
unprovoked_attacks_df.head()

,Country,Case_Number,Date,Year,Type,Area,Location,Activity,Sex,Age,Injury,Fatal_Y_N,Time,Species
1,USA,2018.06.18,6/18/2018,2018.0,Unprovoked,Georgia,"St. Simon Island, Glynn County",Standing,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN
3,AUSTRALIA,2018.06.08,6/8/2018,2018.0,Unprovoked,New South Wales,Arrawarra Headland,Surfing,M,NaN,Minor injury to lower leg,N,NaN,2 m shark
5,AUSTRALIA,2018.06.03.b,6/3/2018,2018.0,Unprovoked,New South Wales,"Flat Rock, Ballina",Kite surfing,M,NaN,"No injury, board bitten",N,NaN,NaN
6,BRAZIL,2018.06.03.a,6/3/2018,2018.0,Unprovoked,Pernambuco,"Piedade Beach, Recife",Swimming,M,18,FATAL,Y,Late afternoon,Tiger shark
7,USA,2018.05.27,5/27/2018,2018.0,Unprovoked,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'"

In [25]:
# Add Month column to extract the month of the attack
unprovoked_attacks_df['Month'] = ''

/Users/giovannacolareta/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [26]:
unprovoked_attacks_df.head(5)

,Country,Case_Number,Date,Year,Type,Area,Location,Activity,Sex,Age,Injury,Fatal_Y_N,Time,Species,Month
1,USA,2018.06.18,6/18/2018,2018.0,Unprovoked,Georgia,"St. Simon Island, Glynn County",Standing,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,
3,AUSTRALIA,2018.06.08,6/8/2018,2018.0,Unprovoked,New South Wales,Arrawarra Headland,Surfing,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,
5,AUSTRALIA,2018.06.03.b,6/3/2018,2018.0,Unprovoked,New South Wales,"Flat Rock, Ballina",Kite surfing,M,NaN,"No injury, board bitten",N,NaN,NaN,
6,BRAZIL,2018.06.03.a,6/3/2018,2018.0,Unprovoked,Pernambuco,"Piedade Beach, Recife",Swimming,M,18,FATAL,Y,Late afternoon,Tiger shark,
7,USA,2018.05.27,5/27/2018,2018.0,Unprovoked,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'",

In [27]:
# Reorder columns
unprovoked_attacks_df = unprovoked_attacks_df.reindex(columns=['Case_Number', 'Date', 'Month', 'Year', 'Type', 'Country', 'Area', 'Location',
                                        'Activity', 'Sex', 'Age', 'Injury', 'Fatal_Y_N', 'Time', 'Species']
                                               )

In [28]:
unprovoked_attacks_df.head(5)

,Case_Number,Date,Month,Year,Type,Country,Area,Location,Activity,Sex,Age,Injury,Fatal_Y_N,Time,Species
1,2018.06.18,6/18/2018,,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,NaN,11,Minor injury to left thigh,N,14h00 -15h00,NaN
3,2018.06.08,6/8/2018,,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,NaN,NaN,Minor injury to lower leg,N,NaN,NaN
5,2018.06.03.b,6/3/2018,,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,NaN,NaN,"No injury, board bitten",N,NaN,NaN
6,2018.06.03.a,6/3/2018,,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,NaN,18,FATAL,Y,Late afternoon,NaN
7,2018.05.27,5/27/2018,,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,NaN,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,NaN

## Cleaning 'Date' column

In [29]:
# Drop rows with a year less than 1950
unprovoked_attacks_2000 = unprovoked_attacks_df[unprovoked_attacks_df["Year"]>=2000]
unprovoked_attacks_2000.head()

,Case_Number,Date,Month,Year,Type,Country,Area,Location,Activity,Sex,Age,Injury,Fatal_Y_N,Time,Species
1,2018.06.18,6/18/2018,,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,NaN,11,Minor injury to left thigh,N,14h00 -15h00,NaN
3,2018.06.08,6/8/2018,,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,NaN,NaN,Minor injury to lower leg,N,NaN,NaN
5,2018.06.03.b,6/3/2018,,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,NaN,NaN,"No injury, board bitten",N,NaN,NaN
6,2018.06.03.a,6/3/2018,,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,NaN,18,FATAL,Y,Late afternoon,NaN
7,2018.05.27,5/27/2018,,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,NaN,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,NaN

In [30]:
unprovoked_attacks_2000['Month'] = unprovoked_attacks_2000['Case_Number'].str[6:7]

/Users/giovannacolareta/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [31]:
unprovoked_attacks_2000.head()

,Case_Number,Date,Month,Year,Type,Country,Area,Location,Activity,Sex,Age,Injury,Fatal_Y_N,Time,Species
1,2018.06.18,6/18/2018,6,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,NaN,11,Minor injury to left thigh,N,14h00 -15h00,NaN
3,2018.06.08,6/8/2018,6,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,NaN,NaN,Minor injury to lower leg,N,NaN,NaN
5,2018.06.03.b,6/3/2018,6,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,NaN,NaN,"No injury, board bitten",N,NaN,NaN
6,2018.06.03.a,6/3/2018,6,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,NaN,18,FATAL,Y,Late afternoon,NaN
7,2018.05.27,5/27/2018,5,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,NaN,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,NaN

In [32]:
# Convert Month column to integer
unprovoked_attacks_2000['Month'].astype(int)

1       6
3       6
5       6
6       6
7       5
       ..
2071    2
2072    2
2074    2
2075    2
2077    1
Name: Month, Length: 1617, dtype: int64

## Extract the Species column

In [33]:
# Reading attacks dataset. Source: https://stackoverflow.com/questions/42339876/error-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xff-in-position-0-in
attacks_raw_df = pd.read_csv(path, encoding='cp1252')
attacks_raw_df.head()

,Country,Case_Number,Date,Year,Type,Area,Location,Activity,Name,Sex,Age,Injury,Fatal_Y_N,Time,Species,Investigator_ or_ Source,pdf,href
0,USA,2018.06.25,6/25/2018,2018.0,Boating,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,USA,2018.06.18,6/18/2018,2018.0,Unprovoked,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,USA,2018.06.09,6/9/2018,2018.0,Invalid,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,AUSTRALIA,2018.06.08,6/8/2018,2018.0,Unprovoked,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,MEXICO,2018.06.04,6/4/2018,2018.0,Provoked,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

In [34]:
species_df = attacks_raw_df.loc[['Case_Number', 'Type', 'Fatal_Y_N', 'Species']]

KeyError: "None of [Index(['Case_Number', 'Type', 'Fatal_Y_N', 'Species'], dtype='object')] are in the [index]"